require 'farkle/scorer'
require 'farkle/singles_scorer'
require 'farkle/multiples_scorer'
require 'farkle/score'
require 'farkle/straights_scorer'
require 'farkle/triple_doubles_scorer'
require 'farkle/double_triples_scorer'
